2023-06-17 18:58:01,227 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2023-06-17 18:58:01,228 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\cibra\AppData\Local\Programs\Python\Python310\lib\site-packages\instabot\bot\bot.py
2023-06-17 18:58:01,228 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2023-06-17 18:58:01,540 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2023-06-17 18:58:01,850 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2023-06-17 18:58:02,106 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2023-06-17 18:58:02,358 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2023-06-17 18:58:02,358 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2023-06-17 18:58:02,358 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2023-06-17 18:58:02,359 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
